[package]
name = "shamirShared"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "shamirShared"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.1"
shamirsecretsharing = "0.1"
hex = "0.4"

[dev-dependencies]
marine-rs-sdk-test = "0.11.0"